-- =====================================================
-- Windmill 완전 데이터베이스 스키마 설정 스크립트 (DB2 최적화판)
-- =====================================================
-- 실행 전 DB2에 연결되어 있는지 확인하세요
-- db2 connect to SAMPLE user db2inst1 using password
--
-- 테이블 생성 순서:
-- 1. 독립적인 테이블들 (외래키가 없는 테이블)
-- 2. 의존성이 있는 테이블들 (외래키가 있는 테이블)
-- 3. 자기참조 외래키는 나중에 ALTER TABLE로 추가
-- 4. 인덱스 생성
-- 5. 기본 데이터 삽입
-- 6. 외래키 제약조건 추가

-- =====================================================
-- 1. 사용자 관리 테이블
-- =====================================================

-- 사용자 테이블
CREATE TABLE USERS (
    USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,  -- 암호화 필수
    TEMP_PASSWORD VARCHAR(255),      -- 임시 비밀번호
    STATUS VARCHAR(20) DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, LOCKED
    IP_RESTRICTION VARCHAR(500),     -- IP 제한 (JSON)
    EXCEL_DOWNLOAD_IP_PATTERN VARCHAR(500), -- 엑셀 다운로드 허용 IP 패턴 (예: 10.240.13.*, * = 전체 허용)
    LAST_LOGIN_TIMESTAMP TIMESTAMP,
    LOGIN_FAIL_COUNT INTEGER DEFAULT 0,  -- 계정 잠금용
    PASSWORD_CHANGE_DATE DATE,
    ACCOUNT_START_DATE DATE,         -- 계정 사용 시작일 (NULL이면 제한 없음)
    ACCOUNT_END_DATE DATE,           -- 계정 사용 종료일 (NULL이면 제한 없음)
    CREATED_BY VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- 사용자 그룹 테이블
CREATE TABLE USER_GROUPS (
    GROUP_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    GROUP_NAME VARCHAR(100) NOT NULL,
    GROUP_DESCRIPTION VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- 사용자-그룹 매핑 테이블 (다중 그룹 지원)
CREATE TABLE USER_GROUP_MAPPING (
    USER_ID VARCHAR(50) NOT NULL,
    GROUP_ID VARCHAR(50) NOT NULL,
    ASSIGNED_BY VARCHAR(50),
    ASSIGNED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (USER_ID, GROUP_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID) ON DELETE CASCADE
);

-- =====================================================
-- 2. 연결 정보 테이블 (SQL_CONTENT에서 참조하므로 먼저 생성)
-- =====================================================

-- 데이터베이스 연결 정보
CREATE TABLE DATABASE_CONNECTION (
    CONNECTION_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    DB_TYPE VARCHAR(20) NOT NULL,
    HOST_IP VARCHAR(45) NOT NULL,
    PORT INTEGER,
    DATABASE_NAME VARCHAR(100),
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    JDBC_DRIVER_FILE VARCHAR(200),
    TEST_SQL VARCHAR(1000),              -- 연결 테스트용 SQL
    CONNECTION_POOL_SETTINGS CLOB,
    CONNECTION_TIMEOUT INTEGER DEFAULT 15,
    QUERY_TIMEOUT INTEGER DEFAULT 600,
    MAX_POOL_SIZE INTEGER DEFAULT 10,
    MIN_POOL_SIZE INTEGER DEFAULT 2,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    MONITORING_ENABLED BOOLEAN DEFAULT FALSE,
    MONITORING_INTERVAL INTEGER DEFAULT 5, -- 5분 (초 단위)
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- SFTP 연결 정보
CREATE TABLE SFTP_CONNECTION (
    SFTP_CONNECTION_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    HOST_IP VARCHAR(45) NOT NULL,
    PORT INTEGER DEFAULT 22,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- =====================================================
-- 3. SQL 템플릿 관련 테이블
-- =====================================================

-- SQL 템플릿 카테고리
CREATE TABLE SQL_TEMPLATE_CATEGORY (
    CATEGORY_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL,
    CATEGORY_DESCRIPTION VARCHAR(500),
    CATEGORY_ORDER INTEGER DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- SQL 템플릿 기본 정보
CREATE TABLE SQL_TEMPLATE (
    TEMPLATE_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    TEMPLATE_NAME VARCHAR(200) NOT NULL,
    TEMPLATE_DESC VARCHAR(500),
    TEMPLATE_TYPE VARCHAR(20) DEFAULT 'SQL' NOT NULL, -- 템플릿 타입 (SQL, INSERT, UPDATE, UPSERT 등)
    SQL_CONTENT CLOB NOT NULL,
    ACCESSIBLE_CONNECTION_IDS VARCHAR(500),
    CHART_MAPPING VARCHAR(50),  -- 차트 매핑 ID (APPL_COUNT, LOCK_WAIT_COUNT, ACTIVE_LOG, FILESYSTEM)
    VERSION INTEGER DEFAULT 1,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    EXECUTION_LIMIT INTEGER DEFAULT 0,
    REFRESH_TIMEOUT INTEGER DEFAULT 0,
    NEWLINE BOOLEAN DEFAULT TRUE,
    AUDIT BOOLEAN DEFAULT FALSE,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- SQL 템플릿 파라미터
CREATE TABLE SQL_TEMPLATE_PARAMETER (
    PARAMETER_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEMPLATE_ID VARCHAR(100) NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(20) DEFAULT 'STRING',
    PARAMETER_ORDER INTEGER DEFAULT 0,
    IS_REQUIRED BOOLEAN DEFAULT FALSE,
    DEFAULT_VALUE VARCHAR(500),
    IS_READONLY BOOLEAN DEFAULT FALSE,
    IS_HIDDEN BOOLEAN DEFAULT FALSE,
    IS_DISABLED BOOLEAN DEFAULT FALSE,
    DESCRIPTION VARCHAR(500),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE
);

-- SQL 템플릿 단축키
CREATE TABLE SQL_TEMPLATE_SHORTCUT (
    SHORTCUT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_TEMPLATE_ID VARCHAR(100) NOT NULL,
    TARGET_TEMPLATE_ID VARCHAR(100) NOT NULL,
    SHORTCUT_KEY VARCHAR(50) NOT NULL,
    SHORTCUT_NAME VARCHAR(100) NOT NULL,
    SHORTCUT_DESCRIPTION VARCHAR(500),
    SOURCE_COLUMN_INDEXES VARCHAR(200),
    AUTO_EXECUTE BOOLEAN DEFAULT TRUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (SOURCE_TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE,
    FOREIGN KEY (TARGET_TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE
);

-- SQL 템플릿-카테고리 매핑 테이블
CREATE TABLE SQL_TEMPLATE_CATEGORY_MAPPING (
    TEMPLATE_ID VARCHAR(100) NOT NULL,
    CATEGORY_ID VARCHAR(50) NOT NULL,
    MAPPING_ORDER INTEGER DEFAULT 0,
    CREATED_BY VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (TEMPLATE_ID, CATEGORY_ID),
    FOREIGN KEY (TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE,
    FOREIGN KEY (CATEGORY_ID) REFERENCES SQL_TEMPLATE_CATEGORY(CATEGORY_ID) ON DELETE CASCADE
);

-- SQL 내용 관리 테이블 (연결별 SQL 내용)
CREATE TABLE SQL_CONTENT (
    TEMPLATE_ID VARCHAR(100) NOT NULL,
    CONNECTION_ID VARCHAR(200) NOT NULL,  -- 연결 ID (쉼표로 구분된 여러 ID 저장 가능)
    SQL_CONTENT CLOB NOT NULL,
    VERSION INTEGER DEFAULT 1,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (TEMPLATE_ID, CONNECTION_ID),  -- 복합 키
    FOREIGN KEY (TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE
);

-- 그룹-카테고리 매핑 테이블
CREATE TABLE GROUP_CATEGORY_MAPPING (
    GROUP_ID VARCHAR(50) NOT NULL,
    CATEGORY_ID VARCHAR(50) NOT NULL,
    GRANTED_BY VARCHAR(50),
    GRANTED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (GROUP_ID, CATEGORY_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID) ON DELETE CASCADE
);

-- 그룹-연결정보 매핑 테이블
CREATE TABLE GROUP_CONNECTION_MAPPING (
    GROUP_ID VARCHAR(50) NOT NULL,
    CONNECTION_ID VARCHAR(100) NOT NULL,
    GRANTED_BY VARCHAR(50),
    GRANTED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (GROUP_ID, CONNECTION_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID) ON DELETE CASCADE
);

-- 감사 로그 테이블
CREATE TABLE AUDIT_LOGS (
    LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID VARCHAR(50),
    ACTION_TYPE VARCHAR(50) NOT NULL,    -- LOGIN, LOGOUT, CREATE, UPDATE, DELETE, EXECUTE
    RESOURCE_TYPE VARCHAR(50),           -- USER, SQL_TEMPLATE, CONNECTION
    RESOURCE_ID VARCHAR(100),            -- 리소스 ID
    OLD_VALUE CLOB,                      -- 변경 전 값
    NEW_VALUE CLOB,                      -- 변경 후 값
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    SESSION_ID VARCHAR(100),
    EXECUTION_TIME INTEGER,              -- 실행 시간 (ms)
    STATUS VARCHAR(20) DEFAULT 'SUCCESS', -- SUCCESS, FAIL, ERROR
    ERROR_MESSAGE VARCHAR(1000),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- 사용자 세션 테이블
CREATE TABLE USER_SESSIONS (
    SESSION_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    LOGIN_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    LAST_ACCESS_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,  -- 세션 만료 체크용
    SESSION_DATA CLOB,                   -- 세션 데이터 (JSON)
    STATUS VARCHAR(20) DEFAULT 'ACTIVE', -- ACTIVE, EXPIRED, LOGOUT
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- =====================================================
-- 4. 로그 테이블
-- =====================================================

-- DeX 로그 테이블 (기존 순서 유지)
CREATE TABLE DEXLOG (
    USER_ID VARCHAR(20),
    IP VARCHAR(20),
    CONN_DB VARCHAR(20) NOT NULL,
    MENU VARCHAR(50),
    SQL_TYPE VARCHAR(20),
    RESULT_ROWS INTEGER,
    SQL_TEXT CLOB(1048576) LOGGED NOT COMPACT,
    RESULT_MSG VARCHAR(2000),
    DURATION INTEGER,
    EXECUTE_DATE TIMESTAMP,
    XML_LOG XML,
    LOG_ID VARCHAR(50)
);

-- 메뉴 실행 로그 테이블 (대시보드용)
CREATE TABLE EXECUTION_LOG (
    LOG_ID VARCHAR(100) NOT NULL PRIMARY KEY, -- 로그 파일에서 사용하는 LOG_ID
    USER_ID VARCHAR(50) NOT NULL,
    TEMPLATE_ID VARCHAR(100) NOT NULL,        -- 템플릿 ID
    CONNECTION_ID VARCHAR(50) NOT NULL,       -- DB 연결 ID
    SQL_TYPE VARCHAR(20),                     -- SELECT, INSERT, UPDATE, DELETE
    EXECUTION_STATUS VARCHAR(20) DEFAULT 'PENDING', -- SUCCESS, FAIL, PENDING
    DURATION INTEGER,                         -- 실행 시간 (ms)
    AFFECTED_ROWS INTEGER,                    -- 영향받은 행 수
    ERROR_MESSAGE VARCHAR(1000),              -- 오류 메시지 (실패 시)
    SQL_CONTENT CLOB,                         -- 실행된 SQL 내용
    EXECUTION_START_TIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    EXECUTION_END_TIME TIMESTAMP,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- =====================================================
-- 5. 시스템 설정 테이블
-- =====================================================

-- 시스템 설정 (system.properties 마이그레이션용)
CREATE TABLE SYSTEM_CONFIG (
    CONFIG_KEY VARCHAR(100) NOT NULL PRIMARY KEY,
    CONFIG_VALUE VARCHAR(500),
    CONFIG_DESC VARCHAR(200),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- =====================================================
-- 6. 인덱스 생성
-- =====================================================

-- 사용자 관리 인덱스
CREATE INDEX IDX_USERS_STATUS ON USERS(STATUS);
CREATE INDEX IDX_USERS_LAST_LOGIN ON USERS(LAST_LOGIN_TIMESTAMP);
CREATE INDEX IDX_USER_GROUP_MAPPING_USER ON USER_GROUP_MAPPING(USER_ID);
CREATE INDEX IDX_USER_GROUP_MAPPING_GROUP ON USER_GROUP_MAPPING(GROUP_ID);

-- 권한 인덱스
CREATE INDEX IDX_GROUP_CATEGORY_MAPPING_GROUP ON GROUP_CATEGORY_MAPPING(GROUP_ID);
CREATE INDEX IDX_GROUP_CATEGORY_MAPPING_CATEGORY ON GROUP_CATEGORY_MAPPING(CATEGORY_ID);
CREATE INDEX IDX_GROUP_CONNECTION_MAPPING_GROUP ON GROUP_CONNECTION_MAPPING(GROUP_ID);
CREATE INDEX IDX_GROUP_CONNECTION_MAPPING_CONNECTION ON GROUP_CONNECTION_MAPPING(CONNECTION_ID);

-- 감사 로그 인덱스
CREATE INDEX IDX_AUDIT_LOGS_USER ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AUDIT_LOGS_ACTION ON AUDIT_LOGS(ACTION_TYPE);
CREATE INDEX IDX_AUDIT_LOGS_RESOURCE ON AUDIT_LOGS(RESOURCE_TYPE, RESOURCE_ID);
CREATE INDEX IDX_AUDIT_LOGS_TIMESTAMP ON AUDIT_LOGS(CREATED_TIMESTAMP);
CREATE INDEX IDX_AUDIT_LOGS_IP ON AUDIT_LOGS(IP_ADDRESS);

-- 세션 인덱스
CREATE INDEX IDX_USER_SESSIONS_USER ON USER_SESSIONS(USER_ID);
CREATE INDEX IDX_USER_SESSIONS_STATUS ON USER_SESSIONS(STATUS);
CREATE INDEX IDX_USER_SESSIONS_LAST_ACCESS ON USER_SESSIONS(LAST_ACCESS_TIMESTAMP);

-- SQL 템플릿 카테고리 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_CATEGORY_ORDER ON SQL_TEMPLATE_CATEGORY(CATEGORY_ORDER);
CREATE INDEX IDX_SQL_TEMPLATE_CATEGORY_STATUS ON SQL_TEMPLATE_CATEGORY(STATUS);

-- SQL 템플릿 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_STATUS ON SQL_TEMPLATE(STATUS);
CREATE INDEX IDX_SQL_TEMPLATE_CREATED ON SQL_TEMPLATE(CREATED_TIMESTAMP);
CREATE INDEX IDX_SQL_TEMPLATE_CHART_MAPPING ON SQL_TEMPLATE(CHART_MAPPING);

-- SQL 내용 인덱스
CREATE INDEX IDX_SQL_CONTENT_TEMPLATE ON SQL_CONTENT(TEMPLATE_ID);
CREATE INDEX IDX_SQL_CONTENT_CONNECTION ON SQL_CONTENT(CONNECTION_ID);
CREATE INDEX IDX_SQL_CONTENT_VERSION ON SQL_CONTENT(VERSION);
CREATE INDEX IDX_SQL_CONTENT_TEMPLATE_CONNECTION ON SQL_CONTENT(TEMPLATE_ID, CONNECTION_ID);

-- SQL 템플릿-카테고리 매핑 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_CATEGORY_MAPPING_TEMPLATE ON SQL_TEMPLATE_CATEGORY_MAPPING(TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_CATEGORY_MAPPING_CATEGORY ON SQL_TEMPLATE_CATEGORY_MAPPING(CATEGORY_ID);
CREATE INDEX IDX_SQL_TEMPLATE_CATEGORY_MAPPING_ORDER ON SQL_TEMPLATE_CATEGORY_MAPPING(MAPPING_ORDER);

-- SQL 템플릿 파라미터 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_PARAMETER_TEMPLATE ON SQL_TEMPLATE_PARAMETER(TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_PARAMETER_ORDER ON SQL_TEMPLATE_PARAMETER(PARAMETER_ORDER);

-- SQL 템플릿 단축키 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_SOURCE ON SQL_TEMPLATE_SHORTCUT(SOURCE_TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_TARGET ON SQL_TEMPLATE_SHORTCUT(TARGET_TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_KEY ON SQL_TEMPLATE_SHORTCUT(SHORTCUT_KEY);
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_ACTIVE ON SQL_TEMPLATE_SHORTCUT(IS_ACTIVE);

-- 연결 정보 인덱스
CREATE INDEX IDX_DATABASE_CONNECTION_TYPE ON DATABASE_CONNECTION(DB_TYPE);
CREATE INDEX IDX_DATABASE_CONNECTION_STATUS ON DATABASE_CONNECTION(STATUS);
CREATE INDEX IDX_DATABASE_CONNECTION_HOST ON DATABASE_CONNECTION(HOST_IP, PORT);
CREATE INDEX IDX_DATABASE_CONNECTION_MONITORING ON DATABASE_CONNECTION(MONITORING_ENABLED);

-- SFTP 연결 인덱스
CREATE INDEX IDX_SFTP_CONNECTION_STATUS ON SFTP_CONNECTION(STATUS);
CREATE INDEX IDX_SFTP_CONNECTION_HOST ON SFTP_CONNECTION(HOST_IP, PORT);

-- 시스템 설정 인덱스
CREATE INDEX IDX_SYSTEM_CONFIG_KEY ON SYSTEM_CONFIG(CONFIG_KEY);

-- DEXLOG 인덱스
CREATE INDEX IDX_DEXLOG_USER ON DEXLOG(USER_ID);
CREATE INDEX IDX_DEXLOG_CONN_DB ON DEXLOG(CONN_DB);
CREATE INDEX IDX_DEXLOG_MENU ON DEXLOG(MENU);
CREATE INDEX IDX_DEXLOG_SQL_TYPE ON DEXLOG(SQL_TYPE);
CREATE INDEX IDX_DEXLOG_EXECUTE_DATE ON DEXLOG(EXECUTE_DATE);
CREATE INDEX IDX_DEXLOG_LOG_ID ON DEXLOG(LOG_ID);

-- =====================================================
-- 7. 기본 SQL 템플릿 카테고리 생성
-- =====================================================

INSERT INTO SQL_TEMPLATE_CATEGORY (CATEGORY_ID, CATEGORY_NAME, CATEGORY_DESCRIPTION, CATEGORY_ORDER, STATUS, CREATED_BY, CREATED_TIMESTAMP) VALUES
('DASHBOARD', '대시보드', '대시보드 관련 SQL 템플릿', 1, 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP),
('REPORT', '리포트', '리포트 관련 SQL 템플릿', 2, 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP),
('MONITORING', '모니터링', '시스템 모니터링 관련 SQL 템플릿', 3, 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP),
('ADMIN', '관리', '시스템 관리 관련 SQL 템플릿', 4, 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP),
('UTILITY', '유틸리티', '유틸리티 관련 SQL 템플릿', 5, 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 8. SQL 템플릿 샘플 데이터는 별도 파일로 분리
-- =====================================================
-- SQL_TEMPLATE_SAMPLES.sql 파일 참조

-- =====================================================
-- 10. 기본 그룹 생성
-- =====================================================

INSERT INTO USER_GROUPS (GROUP_ID, GROUP_NAME, GROUP_DESCRIPTION, STATUS, CREATED_BY, CREATED_TIMESTAMP)
VALUES 
('ADMIN_GROUP', '관리자 그룹', '시스템 관리자 그룹', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP),
('USER_GROUP', '일반 사용자 그룹', '일반 사용자 그룹', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP),
('VIEWER_GROUP', '조회 전용 그룹', '조회만 가능한 사용자 그룹', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 11. 관리자 계정 생성
-- =====================================================

-- 관리자 사용자 생성 (암호화된 비밀번호: 1234)
-- Crypto.crypt("1234") 결과값 사용
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, STATUS, CREATED_BY, CREATED_TIMESTAMP)
VALUES ('admin', '관리자', '1e0ce442a8e20cc64b534494d7aea44e', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP);

-- 관리자를 관리자 그룹에 할당
INSERT INTO USER_GROUP_MAPPING (USER_ID, GROUP_ID, ASSIGNED_BY, ASSIGNED_TIMESTAMP)
VALUES ('admin', 'ADMIN_GROUP', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 12. 관리자 권한 설정 (와일드카드 권한)
-- =====================================================

-- 관리자 그룹에 모든 카테고리 권한 부여
INSERT INTO GROUP_CATEGORY_MAPPING (GROUP_ID, CATEGORY_ID, GRANTED_BY, GRANTED_TIMESTAMP)
SELECT 'ADMIN_GROUP', CATEGORY_ID, 'SYSTEM', CURRENT TIMESTAMP
FROM SQL_TEMPLATE_CATEGORY;

-- 관리자 그룹에 모든 연결 정보 권한 부여
INSERT INTO GROUP_CONNECTION_MAPPING (GROUP_ID, CONNECTION_ID, GRANTED_BY, GRANTED_TIMESTAMP)
SELECT 'ADMIN_GROUP', CONNECTION_ID, 'SYSTEM', CURRENT TIMESTAMP
FROM DATABASE_CONNECTION;

-- =====================================================
-- 13. 테스트 사용자 생성 (선택사항)
-- =====================================================

-- 테스트 사용자 생성 (비밀번호: test123)
-- Crypto.crypt("test123") 결과값 사용
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, STATUS, CREATED_BY, CREATED_TIMESTAMP)
VALUES ('testuser', '테스트 사용자', '1e0ce442a8e20cc64b534494d7aea44e', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP);

-- 테스트 사용자를 일반 사용자 그룹에 할당
INSERT INTO USER_GROUP_MAPPING (USER_ID, GROUP_ID, ASSIGNED_BY, ASSIGNED_TIMESTAMP)
VALUES ('testuser', 'USER_GROUP', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 14. 초기 시스템 설정 데이터 삽입
-- =====================================================


-- SYSTEM_CONFIG 테이블 기본 설정값 삽입 (system.properties 마이그레이션용)
-- 공지사항 내용 (기본값: 빈 문자열)
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, CREATED_DATE, UPDATED_DATE) 
SELECT 'NOTICE_CONTENT', '', '공지사항 내용', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM SYSTEM_CONFIG WHERE CONFIG_KEY = 'NOTICE_CONTENT');

-- 공지사항 활성화 여부 (기본값: false)
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, CREATED_DATE, UPDATED_DATE) 
SELECT 'NOTICE_ENABLED', 'false', '공지사항 활성화 여부 (true/false)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM SYSTEM_CONFIG WHERE CONFIG_KEY = 'NOTICE_ENABLED');

-- 세션 타임아웃 설정
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, CREATED_DATE, UPDATED_DATE) 
SELECT 'SESSION_TIMEOUT', '600', '세션 타임아웃 (분 단위)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM SYSTEM_CONFIG WHERE CONFIG_KEY = 'SESSION_TIMEOUT');

-- 다운로드 IP 패턴 설정
INSERT INTO SYSTEM_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_DESC, CREATED_DATE, UPDATED_DATE) 
SELECT 'DOWNLOAD_IP_PATTERN', '10.240.13.*', '다운로드 허용 IP 패턴 (* = 모든 IP 허용)', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM SYSIBM.SYSDUMMY1
WHERE NOT EXISTS (SELECT 1 FROM SYSTEM_CONFIG WHERE CONFIG_KEY = 'DOWNLOAD_IP_PATTERN');

-- =====================================================
-- 15. 테스트 데이터 삽입 (선택사항)
-- =====================================================

-- 테스트용 데이터베이스 연결 (먼저 삽입)
INSERT INTO DATABASE_CONNECTION (CONNECTION_ID,DB_TYPE,HOST_IP,PORT,DATABASE_NAME,USERNAME,PASSWORD,JDBC_DRIVER_FILE,TEST_SQL,CONNECTION_POOL_SETTINGS,CONNECTION_TIMEOUT,QUERY_TIMEOUT,MAX_POOL_SIZE,MIN_POOL_SIZE,STATUS,MONITORING_ENABLED,MONITORING_INTERVAL,CREATED_BY,CREATED_TIMESTAMP,MODIFIED_BY,MODIFIED_TIMESTAMP) VALUES
	 ('test_db','DB2','192.168.219.116',50000,'SAMPLE','db2inst1','1234','jcc-11.5.0.0.jar','SELECT 1 FROM SYSIBM.SYSDUMMY1',NULL,15,600,10,2,'ACTIVE',FALSE,10,'SYSTEM',CURRENT TIMESTAMP,NULL,CURRENT TIMESTAMP);

-- =====================================================
-- 17. 실제 데이터에 대한 권한 설정 (와일드카드 권한과 별도)
-- =====================================================

-- 관리자 그룹에 모든 카테고리 권한 부여 (중복 방지)
INSERT INTO GROUP_CATEGORY_MAPPING (GROUP_ID, CATEGORY_ID, GRANTED_BY, GRANTED_TIMESTAMP)
SELECT 'ADMIN_GROUP', CATEGORY_ID, 'SYSTEM', CURRENT TIMESTAMP
FROM SQL_TEMPLATE_CATEGORY
WHERE NOT EXISTS (
    SELECT 1 FROM GROUP_CATEGORY_MAPPING 
    WHERE GROUP_ID = 'ADMIN_GROUP' AND CATEGORY_ID = SQL_TEMPLATE_CATEGORY.CATEGORY_ID
);

-- 관리자 그룹에 모든 연결 정보 권한 부여 (중복 방지)
INSERT INTO GROUP_CONNECTION_MAPPING (GROUP_ID, CONNECTION_ID, GRANTED_BY, GRANTED_TIMESTAMP)
SELECT 'ADMIN_GROUP', CONNECTION_ID, 'SYSTEM', CURRENT TIMESTAMP
FROM DATABASE_CONNECTION
WHERE NOT EXISTS (
    SELECT 1 FROM GROUP_CONNECTION_MAPPING 
    WHERE GROUP_ID = 'ADMIN_GROUP' AND CONNECTION_ID = DATABASE_CONNECTION.CONNECTION_ID
);

-- =====================================================
-- 스키마 생성 완료
-- =====================================================
