-- =====================================================
-- Windmill 완전 스키마 설정 스크립트
-- =====================================================
-- 실행 전 DB2에 연결되어 있는지 확인하세요
-- db2 connect to SAMPLE user db2inst1 using password

-- =====================================================
-- 1. 기존 사용자 관리 테이블 (USER_COMPLETE_SETUP.sql에서 생성됨)
-- =====================================================
-- USERS, USER_GROUPS, USER_GROUP_MAPPING
-- SQL_TEMPLATE_PERMISSIONS, CONNECTION_PERMISSIONS
-- AUDIT_LOGS, USER_SESSIONS

-- =====================================================
-- 2. SQL 템플릿 관련 테이블
-- =====================================================

-- SQL 템플릿 기본 정보
CREATE TABLE SQL_TEMPLATE (
    TEMPLATE_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    TEMPLATE_NAME VARCHAR(200) NOT NULL,
    CATEGORY_PATH VARCHAR(500) NOT NULL,
    SQL_CONTENT CLOB NOT NULL,
    VERSION INTEGER DEFAULT 1,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    EXECUTION_LIMIT INTEGER DEFAULT 1000,
    REFRESH_TIMEOUT INTEGER DEFAULT 10,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- SQL 템플릿 파라미터
CREATE TABLE SQL_TEMPLATE_PARAMETER (
    PARAMETER_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEMPLATE_ID VARCHAR(100) NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(20) DEFAULT 'STRING',
    PARAMETER_ORDER INTEGER DEFAULT 0,
    IS_REQUIRED BOOLEAN DEFAULT FALSE,
    DEFAULT_VALUE VARCHAR(500),
    DESCRIPTION VARCHAR(500),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE
);

-- SQL 템플릿 단축키
CREATE TABLE SQL_TEMPLATE_SHORTCUT (
    SHORTCUT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_TEMPLATE_ID VARCHAR(100) NOT NULL,
    TARGET_TEMPLATE_ID VARCHAR(100) NOT NULL,
    SHORTCUT_KEY VARCHAR(50) NOT NULL,
    SHORTCUT_NAME VARCHAR(100) NOT NULL,
    SHORTCUT_DESCRIPTION VARCHAR(500),
    SOURCE_COLUMN_INDEXES VARCHAR(200),
    AUTO_EXECUTE BOOLEAN DEFAULT TRUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (SOURCE_TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE,
    FOREIGN KEY (TARGET_TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE
);

-- =====================================================
-- 3. 연결 정보 테이블
-- =====================================================

-- 데이터베이스 연결 정보
CREATE TABLE DATABASE_CONNECTION (
    CONNECTION_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CONNECTION_NAME VARCHAR(200) NOT NULL,
    DB_TYPE VARCHAR(20) NOT NULL,
    HOST_IP VARCHAR(45) NOT NULL,
    PORT INTEGER,
    DATABASE_NAME VARCHAR(100),
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    JDBC_DRIVER_FILE VARCHAR(200),
    CONNECTION_POOL_SETTINGS CLOB,
    CONNECTION_TIMEOUT INTEGER DEFAULT 15,
    QUERY_TIMEOUT INTEGER DEFAULT 600,
    MAX_POOL_SIZE INTEGER DEFAULT 10,
    MIN_POOL_SIZE INTEGER DEFAULT 2,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    LAST_CONNECTION_TEST TIMESTAMP,
    CONNECTION_TEST_RESULT VARCHAR(20),
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- SFTP 연결 정보
CREATE TABLE SFTP_CONNECTION (
    SFTP_CONNECTION_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CONNECTION_NAME VARCHAR(200) NOT NULL,
    HOST_IP VARCHAR(45) NOT NULL,
    PORT INTEGER DEFAULT 22,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255),
    PRIVATE_KEY_PATH VARCHAR(500),
    REMOTE_PATH VARCHAR(500),
    CONNECTION_TIMEOUT INTEGER DEFAULT 30,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    LAST_CONNECTION_TEST TIMESTAMP,
    CONNECTION_TEST_RESULT VARCHAR(20),
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- =====================================================
-- 4. 시스템 설정 테이블
-- =====================================================

-- 시스템 설정
CREATE TABLE SYSTEM_SETTING (
    SETTING_KEY VARCHAR(100) NOT NULL PRIMARY KEY,
    SETTING_VALUE CLOB NOT NULL,
    SETTING_TYPE VARCHAR(20) DEFAULT 'STRING',
    DESCRIPTION VARCHAR(500),
    CATEGORY VARCHAR(50) DEFAULT 'GENERAL',
    IS_ENCRYPTED BOOLEAN DEFAULT FALSE,
    IS_SYSTEM BOOLEAN DEFAULT FALSE,
    IS_REQUIRED BOOLEAN DEFAULT FALSE,
    DEFAULT_VALUE CLOB,
    VALIDATION_RULE VARCHAR(200),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- =====================================================
-- 5. 인덱스 생성
-- =====================================================

-- SQL_TEMPLATE 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_CATEGORY ON SQL_TEMPLATE(CATEGORY_PATH);
CREATE INDEX IDX_SQL_TEMPLATE_STATUS ON SQL_TEMPLATE(STATUS);
CREATE INDEX IDX_SQL_TEMPLATE_CREATED ON SQL_TEMPLATE(CREATED_TIMESTAMP);

-- SQL_TEMPLATE_PARAMETER 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_PARAMETER_TEMPLATE ON SQL_TEMPLATE_PARAMETER(TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_PARAMETER_ORDER ON SQL_TEMPLATE_PARAMETER(PARAMETER_ORDER);

-- SQL_TEMPLATE_SHORTCUT 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_SOURCE ON SQL_TEMPLATE_SHORTCUT(SOURCE_TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_TARGET ON SQL_TEMPLATE_SHORTCUT(TARGET_TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_KEY ON SQL_TEMPLATE_SHORTCUT(SHORTCUT_KEY);
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_ACTIVE ON SQL_TEMPLATE_SHORTCUT(IS_ACTIVE);

-- DATABASE_CONNECTION 인덱스
CREATE INDEX IDX_DATABASE_CONNECTION_TYPE ON DATABASE_CONNECTION(DB_TYPE);
CREATE INDEX IDX_DATABASE_CONNECTION_STATUS ON DATABASE_CONNECTION(STATUS);
CREATE INDEX IDX_DATABASE_CONNECTION_HOST ON DATABASE_CONNECTION(HOST_IP, PORT);

-- SFTP_CONNECTION 인덱스
CREATE INDEX IDX_SFTP_CONNECTION_STATUS ON SFTP_CONNECTION(STATUS);
CREATE INDEX IDX_SFTP_CONNECTION_HOST ON SFTP_CONNECTION(HOST_IP, PORT);

-- SYSTEM_SETTING 인덱스
CREATE INDEX IDX_SYSTEM_SETTING_CATEGORY ON SYSTEM_SETTING(CATEGORY);
CREATE INDEX IDX_SYSTEM_SETTING_SYSTEM ON SYSTEM_SETTING(IS_SYSTEM);

-- =====================================================
-- 6. 기존 권한 테이블과의 외래키 연결
-- =====================================================

-- SQL_TEMPLATE_PERMISSIONS 테이블 수정 (기존 테이블이 있다면)
-- ALTER TABLE SQL_TEMPLATE_PERMISSIONS 
-- ADD CONSTRAINT FK_SQL_TEMPLATE_PERMISSIONS_TEMPLATE 
-- FOREIGN KEY (TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE;

-- CONNECTION_PERMISSIONS 테이블 수정 (기존 테이블이 있다면)
-- ALTER TABLE CONNECTION_PERMISSIONS 
-- ADD CONSTRAINT FK_CONNECTION_PERMISSIONS_DB_CONNECTION 
-- FOREIGN KEY (CONNECTION_ID) REFERENCES DATABASE_CONNECTION(CONNECTION_ID) ON DELETE CASCADE;

-- =====================================================
-- 7. 초기 시스템 설정 데이터 삽입
-- =====================================================

INSERT INTO SYSTEM_SETTING (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, CATEGORY, IS_SYSTEM, IS_REQUIRED) VALUES
('ROOT_PATH', '${system.root.path}', 'STRING', '시스템 루트 경로', 'SYSTEM', TRUE, TRUE),
('TIMEOUT', '600', 'NUMBER', '기본 타임아웃 (초)', 'PERFORMANCE', TRUE, TRUE),
('LOG_DB', 'logDB', 'STRING', '로그 데이터베이스명', 'SYSTEM', TRUE, TRUE),
('DOWNLOAD_IP_PATTERN', '10.240.13.*', 'STRING', '다운로드 허용 IP 패턴', 'SECURITY', TRUE, TRUE),
('JDBC_PATH', '${system.root.path}/jdbc', 'STRING', 'JDBC 드라이버 경로', 'SYSTEM', TRUE, TRUE),
('CONNECTION_PATH', '${system.root.path}/Connection', 'STRING', '연결 정보 경로', 'SYSTEM', TRUE, TRUE),
('SRC_PATH', '${system.root.path}/src', 'STRING', 'SQL 소스 경로', 'SYSTEM', TRUE, TRUE),
('USER_PATH', '${system.root.path}/user', 'STRING', '사용자 정보 경로', 'SYSTEM', TRUE, TRUE),
('TEMP_PATH', '${system.root.path}/temp', 'STRING', '임시 파일 경로', 'SYSTEM', TRUE, TRUE),
('TEXT_LIMIT', '10000', 'NUMBER', '텍스트 입력 제한', 'UI', TRUE, TRUE),
('CHART_REFRESH_INTERVAL', '10', 'NUMBER', '차트 새로고침 간격 (초)', 'UI', TRUE, TRUE);

-- =====================================================
-- 8. 테스트 데이터 삽입 (선택사항)
-- =====================================================

-- 테스트용 SQL 템플릿
INSERT INTO SQL_TEMPLATE (TEMPLATE_ID, TEMPLATE_NAME, CATEGORY_PATH, SQL_CONTENT, CREATED_BY) VALUES
('test_sql', '테스트 SQL', '001_DashBoard', 'SELECT * FROM DUAL', 'SYSTEM');

-- 테스트용 SQL 템플릿 파라미터
INSERT INTO SQL_TEMPLATE_PARAMETER (TEMPLATE_ID, PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_ORDER, IS_REQUIRED, DESCRIPTION) VALUES
('test_sql', 'startDate', 'DATE', 1, TRUE, '시작 날짜'),
('test_sql', 'endDate', 'DATE', 2, TRUE, '종료 날짜'),
('test_sql', 'userId', 'STRING', 3, FALSE, '사용자 ID');

-- 테스트용 SQL 템플릿 단축키 (TARGET_TEMPLATE_ID도 존재하는 템플릿이어야 함)
-- INSERT INTO SQL_TEMPLATE_SHORTCUT (SOURCE_TEMPLATE_ID, TARGET_TEMPLATE_ID, SHORTCUT_KEY, SHORTCUT_NAME, SOURCE_COLUMN_INDEXES, AUTO_EXECUTE) VALUES
-- ('test_sql', 'detail_sql', 'F1', '상세보기', '0,1', TRUE);

-- 테스트용 데이터베이스 연결
INSERT INTO DATABASE_CONNECTION (CONNECTION_ID, CONNECTION_NAME, DB_TYPE, HOST_IP, PORT, DATABASE_NAME, USERNAME, PASSWORD, CREATED_BY) VALUES
('test_db', '테스트 DB', 'DB2', 'localhost', 50000, 'SAMPLE', 'db2inst1', 'password', 'SYSTEM');

-- =====================================================
-- 9. 생성 확인 쿼리
-- =====================================================

-- 생성된 테이블 목록 확인
SELECT 
    '=== 생성된 테이블 목록 ===' as INFO,
    TABNAME as TABLE_NAME,
    TABSCHEMA as SCHEMA_NAME
FROM SYSCAT.TABLES 
WHERE TABSCHEMA = CURRENT SCHEMA 
AND TABNAME IN ('SQL_TEMPLATE', 'SQL_TEMPLATE_PARAMETER', 'SQL_TEMPLATE_SHORTCUT', 
                'DATABASE_CONNECTION', 'SFTP_CONNECTION', 'SYSTEM_SETTING')
ORDER BY TABNAME;

-- SQL 템플릿 테이블 구조 확인
SELECT 
    '=== SQL_TEMPLATE 테이블 구조 ===' as INFO,
    COLNAME as COLUMN_NAME,
    TYPENAME as DATA_TYPE,
    LENGTH,
    NULLS as IS_NULLABLE
FROM SYSCAT.COLUMNS 
WHERE TABNAME = 'SQL_TEMPLATE' 
AND TABSCHEMA = CURRENT SCHEMA
ORDER BY COLNO;

-- 시스템 설정 확인
SELECT 
    '=== 시스템 설정 확인 ===' as INFO,
    SETTING_KEY,
    SETTING_VALUE,
    SETTING_TYPE,
    CATEGORY
FROM SYSTEM_SETTING
ORDER BY CATEGORY, SETTING_KEY;

-- =====================================================
-- 10. 권한 설정 (선택사항)
-- =====================================================

-- 관리자 그룹에 모든 SQL 템플릿 권한 부여 (기존 테이블이 있는 경우에만)
-- INSERT INTO SQL_TEMPLATE_PERMISSIONS (GROUP_ID, TEMPLATE_ID, ACCESS_TYPE, FOLDER_PATH, GRANTED_BY, GRANTED_TIMESTAMP)
-- SELECT 'ADMIN_GROUP', TEMPLATE_ID, 'ADMIN', CATEGORY_PATH, 'SYSTEM', CURRENT TIMESTAMP
-- FROM SQL_TEMPLATE
-- WHERE NOT EXISTS (
--     SELECT 1 FROM SQL_TEMPLATE_PERMISSIONS 
--     WHERE GROUP_ID = 'ADMIN_GROUP' AND TEMPLATE_ID = SQL_TEMPLATE.TEMPLATE_ID
-- );

-- 관리자 그룹에 모든 연결 정보 권한 부여 (기존 테이블이 있는 경우에만)
-- INSERT INTO CONNECTION_PERMISSIONS (GROUP_ID, CONNECTION_ID, ACCESS_TYPE, GRANTED_BY, GRANTED_TIMESTAMP)
-- SELECT 'ADMIN_GROUP', CONNECTION_ID, 'ADMIN', 'SYSTEM', CURRENT TIMESTAMP
-- FROM DATABASE_CONNECTION
-- WHERE NOT EXISTS (
--     SELECT 1 FROM CONNECTION_PERMISSIONS 
--     WHERE GROUP_ID = 'ADMIN_GROUP' AND CONNECTION_ID = DATABASE_CONNECTION.CONNECTION_ID
-- );

-- =====================================================
-- 완료 메시지
-- =====================================================

SELECT 'Windmill 완전 스키마 설정이 완료되었습니다.' as MESSAGE FROM SYSIBM.SYSDUMMY1;
