-- =====================================================
-- Windmill 완전 데이터베이스 스키마 설정 스크립트
-- =====================================================
-- 실행 전 DB2에 연결되어 있는지 확인하세요
-- db2 connect to SAMPLE user db2inst1 using password

-- =====================================================
-- 1. 사용자 관리 테이블
-- =====================================================

-- 사용자 테이블
CREATE TABLE USERS (
    USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,  -- 암호화 필수
    TEMP_PASSWORD VARCHAR(255),      -- 임시 비밀번호
    STATUS VARCHAR(20) DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, LOCKED
    IP_RESTRICTION VARCHAR(500),     -- IP 제한 (JSON)
    LAST_LOGIN_TIMESTAMP TIMESTAMP,
    LOGIN_FAIL_COUNT INTEGER DEFAULT 0,  -- 계정 잠금용
    PASSWORD_CHANGE_DATE DATE,
    CREATED_BY VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- 사용자 그룹 테이블
CREATE TABLE USER_GROUPS (
    GROUP_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    GROUP_NAME VARCHAR(100) NOT NULL,
    GROUP_DESCRIPTION VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- 사용자-그룹 매핑 테이블 (단일 그룹 제약)
CREATE TABLE USER_GROUP_MAPPING (
    USER_ID VARCHAR(50) NOT NULL,
    GROUP_ID VARCHAR(50) NOT NULL,
    ASSIGNED_BY VARCHAR(50),
    ASSIGNED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (USER_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID) ON DELETE CASCADE
);

-- SQL 템플릿 권한 테이블
CREATE TABLE SQL_TEMPLATE_PERMISSIONS (
    GROUP_ID VARCHAR(50) NOT NULL,
    TEMPLATE_ID VARCHAR(100) NOT NULL,   -- SQL 파일명 (와일드카드 '*' 허용)
    ACCESS_TYPE VARCHAR(20) DEFAULT 'READ', -- READ, WRITE, DELETE, ADMIN
    FOLDER_PATH VARCHAR(200),            -- 폴더 경로
    GRANTED_BY VARCHAR(50),
    GRANTED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (GROUP_ID, TEMPLATE_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID) ON DELETE CASCADE
);

-- 연결 정보 권한 테이블
CREATE TABLE CONNECTION_PERMISSIONS (
    GROUP_ID VARCHAR(50) NOT NULL,
    CONNECTION_ID VARCHAR(100) NOT NULL,  -- 연결 정보 ID (와일드카드 '*' 허용)
    ACCESS_TYPE VARCHAR(20) DEFAULT 'READ', -- READ, WRITE, DELETE, ADMIN
    GRANTED_BY VARCHAR(50),
    GRANTED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (GROUP_ID, CONNECTION_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID) ON DELETE CASCADE
);

-- 감사 로그 테이블
CREATE TABLE AUDIT_LOGS (
    LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID VARCHAR(50),
    ACTION_TYPE VARCHAR(50) NOT NULL,    -- LOGIN, LOGOUT, CREATE, UPDATE, DELETE, EXECUTE
    RESOURCE_TYPE VARCHAR(50),           -- USER, SQL_TEMPLATE, CONNECTION
    RESOURCE_ID VARCHAR(100),            -- 리소스 ID
    OLD_VALUE CLOB,                      -- 변경 전 값
    NEW_VALUE CLOB,                      -- 변경 후 값
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    SESSION_ID VARCHAR(100),
    EXECUTION_TIME INTEGER,              -- 실행 시간 (ms)
    STATUS VARCHAR(20) DEFAULT 'SUCCESS', -- SUCCESS, FAIL, ERROR
    ERROR_MESSAGE VARCHAR(1000),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- 사용자 세션 테이블
CREATE TABLE USER_SESSIONS (
    SESSION_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    LOGIN_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    LAST_ACCESS_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,  -- 세션 만료 체크용
    SESSION_DATA CLOB,                   -- 세션 데이터 (JSON)
    STATUS VARCHAR(20) DEFAULT 'ACTIVE', -- ACTIVE, EXPIRED, LOGOUT
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- =====================================================
-- 2. SQL 템플릿 관련 테이블
-- =====================================================

-- SQL 템플릿 기본 정보
CREATE TABLE SQL_TEMPLATE (
    TEMPLATE_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    TEMPLATE_NAME VARCHAR(200) NOT NULL,
    CATEGORY_PATH VARCHAR(500) NOT NULL,
    SQL_CONTENT CLOB NOT NULL,
    VERSION INTEGER DEFAULT 1,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    EXECUTION_LIMIT INTEGER DEFAULT 1000,
    REFRESH_TIMEOUT INTEGER DEFAULT 10,
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- SQL 템플릿 파라미터
CREATE TABLE SQL_TEMPLATE_PARAMETER (
    PARAMETER_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEMPLATE_ID VARCHAR(100) NOT NULL,
    PARAMETER_NAME VARCHAR(100) NOT NULL,
    PARAMETER_TYPE VARCHAR(20) DEFAULT 'STRING',
    PARAMETER_ORDER INTEGER DEFAULT 0,
    IS_REQUIRED BOOLEAN DEFAULT FALSE,
    DEFAULT_VALUE VARCHAR(500),
    DESCRIPTION VARCHAR(500),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE
);

-- SQL 템플릿 단축키
CREATE TABLE SQL_TEMPLATE_SHORTCUT (
    SHORTCUT_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SOURCE_TEMPLATE_ID VARCHAR(100) NOT NULL,
    TARGET_TEMPLATE_ID VARCHAR(100) NOT NULL,
    SHORTCUT_KEY VARCHAR(50) NOT NULL,
    SHORTCUT_NAME VARCHAR(100) NOT NULL,
    SHORTCUT_DESCRIPTION VARCHAR(500),
    SOURCE_COLUMN_INDEXES VARCHAR(200),
    AUTO_EXECUTE BOOLEAN DEFAULT TRUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (SOURCE_TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE,
    FOREIGN KEY (TARGET_TEMPLATE_ID) REFERENCES SQL_TEMPLATE(TEMPLATE_ID) ON DELETE CASCADE
);

-- =====================================================
-- 3. 연결 정보 테이블
-- =====================================================

-- 데이터베이스 연결 정보
CREATE TABLE DATABASE_CONNECTION (
    CONNECTION_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CONNECTION_NAME VARCHAR(200) NOT NULL,
    DB_TYPE VARCHAR(20) NOT NULL,
    HOST_IP VARCHAR(45) NOT NULL,
    PORT INTEGER,
    DATABASE_NAME VARCHAR(100),
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    JDBC_DRIVER_FILE VARCHAR(200),
    TEST_SQL VARCHAR(1000),              -- 연결 테스트용 SQL
    CONNECTION_POOL_SETTINGS CLOB,
    CONNECTION_TIMEOUT INTEGER DEFAULT 15,
    QUERY_TIMEOUT INTEGER DEFAULT 600,
    MAX_POOL_SIZE INTEGER DEFAULT 10,
    MIN_POOL_SIZE INTEGER DEFAULT 2,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    LAST_CONNECTION_TEST TIMESTAMP,
    CONNECTION_TEST_RESULT VARCHAR(20),
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- SFTP 연결 정보
CREATE TABLE SFTP_CONNECTION (
    SFTP_CONNECTION_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    CONNECTION_NAME VARCHAR(200) NOT NULL,
    HOST_IP VARCHAR(45) NOT NULL,
    PORT INTEGER DEFAULT 22,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255),
    PRIVATE_KEY_PATH VARCHAR(500),
    REMOTE_PATH VARCHAR(500),
    CONNECTION_TIMEOUT INTEGER DEFAULT 30,
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    LAST_CONNECTION_TEST TIMESTAMP,
    CONNECTION_TEST_RESULT VARCHAR(20),
    CREATED_BY VARCHAR(50) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- =====================================================
-- 4. 시스템 설정 테이블
-- =====================================================

-- 시스템 설정
CREATE TABLE SYSTEM_SETTING (
    SETTING_KEY VARCHAR(100) NOT NULL PRIMARY KEY,
    SETTING_VALUE CLOB NOT NULL,
    SETTING_TYPE VARCHAR(20) DEFAULT 'STRING',
    DESCRIPTION VARCHAR(500),
    CATEGORY VARCHAR(50) DEFAULT 'GENERAL',
    IS_ENCRYPTED BOOLEAN DEFAULT FALSE,
    IS_SYSTEM BOOLEAN DEFAULT FALSE,
    IS_REQUIRED BOOLEAN DEFAULT FALSE,
    DEFAULT_VALUE CLOB,
    VALIDATION_RULE VARCHAR(200),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- =====================================================
-- 5. 인덱스 생성
-- =====================================================

-- 사용자 관리 인덱스
CREATE INDEX IDX_USERS_STATUS ON USERS(STATUS);
CREATE INDEX IDX_USERS_LAST_LOGIN ON USERS(LAST_LOGIN_TIMESTAMP);
CREATE INDEX IDX_USER_GROUP_MAPPING_USER ON USER_GROUP_MAPPING(USER_ID);
CREATE INDEX IDX_USER_GROUP_MAPPING_GROUP ON USER_GROUP_MAPPING(GROUP_ID);

-- 권한 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_PERMISSIONS_GROUP ON SQL_TEMPLATE_PERMISSIONS(GROUP_ID);
CREATE INDEX IDX_SQL_TEMPLATE_PERMISSIONS_TEMPLATE ON SQL_TEMPLATE_PERMISSIONS(TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_PERMISSIONS_FOLDER ON SQL_TEMPLATE_PERMISSIONS(FOLDER_PATH);
CREATE INDEX IDX_CONNECTION_PERMISSIONS_GROUP ON CONNECTION_PERMISSIONS(GROUP_ID);
CREATE INDEX IDX_CONNECTION_PERMISSIONS_CONN ON CONNECTION_PERMISSIONS(CONNECTION_ID);

-- 감사 로그 인덱스
CREATE INDEX IDX_AUDIT_LOGS_USER ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AUDIT_LOGS_ACTION ON AUDIT_LOGS(ACTION_TYPE);
CREATE INDEX IDX_AUDIT_LOGS_RESOURCE ON AUDIT_LOGS(RESOURCE_TYPE, RESOURCE_ID);
CREATE INDEX IDX_AUDIT_LOGS_TIMESTAMP ON AUDIT_LOGS(CREATED_TIMESTAMP);
CREATE INDEX IDX_AUDIT_LOGS_IP ON AUDIT_LOGS(IP_ADDRESS);

-- 세션 인덱스
CREATE INDEX IDX_USER_SESSIONS_USER ON USER_SESSIONS(USER_ID);
CREATE INDEX IDX_USER_SESSIONS_STATUS ON USER_SESSIONS(STATUS);
CREATE INDEX IDX_USER_SESSIONS_LAST_ACCESS ON USER_SESSIONS(LAST_ACCESS_TIMESTAMP);

-- SQL 템플릿 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_CATEGORY ON SQL_TEMPLATE(CATEGORY_PATH);
CREATE INDEX IDX_SQL_TEMPLATE_STATUS ON SQL_TEMPLATE(STATUS);
CREATE INDEX IDX_SQL_TEMPLATE_CREATED ON SQL_TEMPLATE(CREATED_TIMESTAMP);

-- SQL 템플릿 파라미터 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_PARAMETER_TEMPLATE ON SQL_TEMPLATE_PARAMETER(TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_PARAMETER_ORDER ON SQL_TEMPLATE_PARAMETER(PARAMETER_ORDER);

-- SQL 템플릿 단축키 인덱스
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_SOURCE ON SQL_TEMPLATE_SHORTCUT(SOURCE_TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_TARGET ON SQL_TEMPLATE_SHORTCUT(TARGET_TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_KEY ON SQL_TEMPLATE_SHORTCUT(SHORTCUT_KEY);
CREATE INDEX IDX_SQL_TEMPLATE_SHORTCUT_ACTIVE ON SQL_TEMPLATE_SHORTCUT(IS_ACTIVE);

-- 연결 정보 인덱스
CREATE INDEX IDX_DATABASE_CONNECTION_TYPE ON DATABASE_CONNECTION(DB_TYPE);
CREATE INDEX IDX_DATABASE_CONNECTION_STATUS ON DATABASE_CONNECTION(STATUS);
CREATE INDEX IDX_DATABASE_CONNECTION_HOST ON DATABASE_CONNECTION(HOST_IP, PORT);

-- SFTP 연결 인덱스
CREATE INDEX IDX_SFTP_CONNECTION_STATUS ON SFTP_CONNECTION(STATUS);
CREATE INDEX IDX_SFTP_CONNECTION_HOST ON SFTP_CONNECTION(HOST_IP, PORT);

-- 시스템 설정 인덱스
CREATE INDEX IDX_SYSTEM_SETTING_CATEGORY ON SYSTEM_SETTING(CATEGORY);
CREATE INDEX IDX_SYSTEM_SETTING_SYSTEM ON SYSTEM_SETTING(IS_SYSTEM);

-- =====================================================
-- 6. 외래키 제약 조건 연결 (데이터 삽입 후 추가)
-- =====================================================

-- 주의: SQL_TEMPLATE_PERMISSIONS와 CONNECTION_PERMISSIONS 테이블의 
-- TEMPLATE_ID와 CONNECTION_ID는 와일드카드 '*' 값을 허용하므로
-- 외래키 제약 조건을 설정하지 않습니다.
-- 애플리케이션 레벨에서 데이터 무결성을 보장합니다.

-- =====================================================
-- 6. 기본 그룹 생성
-- =====================================================

INSERT INTO USER_GROUPS (GROUP_ID, GROUP_NAME, GROUP_DESCRIPTION, STATUS, CREATED_BY, CREATED_TIMESTAMP)
VALUES 
('ADMIN_GROUP', '관리자 그룹', '시스템 관리자 그룹', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP),
('USER_GROUP', '일반 사용자 그룹', '일반 사용자 그룹', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP),
('VIEWER_GROUP', '조회 전용 그룹', '조회만 가능한 사용자 그룹', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 7. 관리자 계정 생성
-- =====================================================

-- 관리자 사용자 생성 (암호화된 비밀번호: 1234)
-- Crypto.crypt("1234") 결과값 사용
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, STATUS, CREATED_BY, CREATED_TIMESTAMP)
VALUES ('admin', '관리자', '1e0ce442a8e20cc64b534494d7aea44e', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP);

-- 관리자를 관리자 그룹에 할당
INSERT INTO USER_GROUP_MAPPING (USER_ID, GROUP_ID, ASSIGNED_BY, ASSIGNED_TIMESTAMP)
VALUES ('admin', 'ADMIN_GROUP', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 8. 관리자 권한 설정 (와일드카드 권한)
-- =====================================================

-- 관리자에게 모든 SQL 템플릿 권한 부여 (와일드카드)
INSERT INTO SQL_TEMPLATE_PERMISSIONS (GROUP_ID, TEMPLATE_ID, ACCESS_TYPE, FOLDER_PATH, GRANTED_BY, GRANTED_TIMESTAMP)
VALUES ('ADMIN_GROUP', '*', 'ADMIN', '*', 'SYSTEM', CURRENT TIMESTAMP);

-- 관리자에게 모든 연결 정보 권한 부여 (와일드카드)
INSERT INTO CONNECTION_PERMISSIONS (GROUP_ID, CONNECTION_ID, ACCESS_TYPE, GRANTED_BY, GRANTED_TIMESTAMP)
VALUES ('ADMIN_GROUP', '*', 'ADMIN', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 9. 테스트 사용자 생성 (선택사항)
-- =====================================================

-- 테스트 사용자 생성 (비밀번호: test123)
-- Crypto.crypt("test123") 결과값 사용
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, STATUS, CREATED_BY, CREATED_TIMESTAMP)
VALUES ('testuser', '테스트 사용자', '1e0ce442a8e20cc64b534494d7aea44e', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP);

-- 테스트 사용자를 일반 사용자 그룹에 할당
INSERT INTO USER_GROUP_MAPPING (USER_ID, GROUP_ID, ASSIGNED_BY, ASSIGNED_TIMESTAMP)
VALUES ('testuser', 'USER_GROUP', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 10. 초기 시스템 설정 데이터 삽입
-- =====================================================

INSERT INTO SYSTEM_SETTING (SETTING_KEY, SETTING_VALUE, SETTING_TYPE, DESCRIPTION, CATEGORY, IS_SYSTEM, IS_REQUIRED) VALUES
('ROOT_PATH', '${system.root.path}', 'STRING', '시스템 루트 경로', 'SYSTEM', TRUE, TRUE),
('TIMEOUT', '600', 'NUMBER', '기본 타임아웃 (초)', 'PERFORMANCE', TRUE, TRUE),
('LOG_DB', 'logDB', 'STRING', '로그 데이터베이스명', 'SYSTEM', TRUE, TRUE),
('DOWNLOAD_IP_PATTERN', '10.240.13.*', 'STRING', '다운로드 허용 IP 패턴', 'SECURITY', TRUE, TRUE),
('JDBC_PATH', '${system.root.path}/jdbc', 'STRING', 'JDBC 드라이버 경로', 'SYSTEM', TRUE, TRUE),
('CONNECTION_PATH', '${system.root.path}/Connection', 'STRING', '연결 정보 경로', 'SYSTEM', TRUE, TRUE),
('SRC_PATH', '${system.root.path}/src', 'STRING', 'SQL 소스 경로', 'SYSTEM', TRUE, TRUE),
('USER_PATH', '${system.root.path}/user', 'STRING', '사용자 정보 경로', 'SYSTEM', TRUE, TRUE),
('TEMP_PATH', '${system.root.path}/temp', 'STRING', '임시 파일 경로', 'SYSTEM', TRUE, TRUE),
('TEXT_LIMIT', '10000', 'NUMBER', '텍스트 입력 제한', 'UI', TRUE, TRUE),
('CHART_REFRESH_INTERVAL', '10', 'NUMBER', '차트 새로고침 간격 (초)', 'UI', TRUE, TRUE);

-- =====================================================
-- 11. 테스트 데이터 삽입 (선택사항)
-- =====================================================

-- 테스트용 SQL 템플릿
INSERT INTO SQL_TEMPLATE (TEMPLATE_ID, TEMPLATE_NAME, CATEGORY_PATH, SQL_CONTENT, CREATED_BY) VALUES
('test_sql', '테스트 SQL', '001_DashBoard', 'SELECT * FROM DUAL', 'SYSTEM');

-- 테스트용 SQL 템플릿 파라미터
INSERT INTO SQL_TEMPLATE_PARAMETER (TEMPLATE_ID, PARAMETER_NAME, PARAMETER_TYPE, PARAMETER_ORDER, IS_REQUIRED, DESCRIPTION) VALUES
('test_sql', 'startDate', 'DATE', 1, TRUE, '시작 날짜'),
('test_sql', 'endDate', 'DATE', 2, TRUE, '종료 날짜'),
('test_sql', 'userId', 'STRING', 3, FALSE, '사용자 ID');

-- 테스트용 SQL 템플릿 단축키
INSERT INTO SQL_TEMPLATE_SHORTCUT (SOURCE_TEMPLATE_ID, TARGET_TEMPLATE_ID, SHORTCUT_KEY, SHORTCUT_NAME, SOURCE_COLUMN_INDEXES, AUTO_EXECUTE) VALUES
('test_sql', 'test_sql', 'F1', '상세보기', '0,1', TRUE);

-- 테스트용 데이터베이스 연결
INSERT INTO DATABASE_CONNECTION (CONNECTION_ID, CONNECTION_NAME, DB_TYPE, HOST_IP, PORT, DATABASE_NAME, USERNAME, PASSWORD, CREATED_BY) VALUES
('test_db', '테스트 DB', 'DB2', 'localhost', 50000, 'SAMPLE', 'db2inst1', 'password', 'SYSTEM');

-- =====================================================
-- 12. 실제 데이터에 대한 권한 설정 (와일드카드 권한과 별도)
-- =====================================================

-- 관리자 그룹에 실제 SQL 템플릿 권한 부여 (와일드카드 권한과 별도로 설정)
INSERT INTO SQL_TEMPLATE_PERMISSIONS (GROUP_ID, TEMPLATE_ID, ACCESS_TYPE, FOLDER_PATH, GRANTED_BY, GRANTED_TIMESTAMP)
SELECT 'ADMIN_GROUP', TEMPLATE_ID, 'ADMIN', CATEGORY_PATH, 'SYSTEM', CURRENT TIMESTAMP
FROM SQL_TEMPLATE
WHERE NOT EXISTS (
    SELECT 1 FROM SQL_TEMPLATE_PERMISSIONS 
    WHERE GROUP_ID = 'ADMIN_GROUP' AND TEMPLATE_ID = SQL_TEMPLATE.TEMPLATE_ID
);

-- 관리자 그룹에 실제 연결 정보 권한 부여 (와일드카드 권한과 별도로 설정)
INSERT INTO CONNECTION_PERMISSIONS (GROUP_ID, CONNECTION_ID, ACCESS_TYPE, GRANTED_BY, GRANTED_TIMESTAMP)
SELECT 'ADMIN_GROUP', CONNECTION_ID, 'ADMIN', 'SYSTEM', CURRENT TIMESTAMP
FROM DATABASE_CONNECTION
WHERE NOT EXISTS (
    SELECT 1 FROM CONNECTION_PERMISSIONS 
    WHERE GROUP_ID = 'ADMIN_GROUP' AND CONNECTION_ID = DATABASE_CONNECTION.CONNECTION_ID
);

-- =====================================================
-- 13. 완료 메시지
-- =====================================================

SELECT 'Windmill 완전 데이터베이스 스키마 설정이 완료되었습니다.' as MESSAGE FROM SYSIBM.SYSDUMMY1;

