-- =====================================================
-- Windmill 사용자 관리 시스템 완전 설정 스크립트
-- =====================================================
-- 실행 전 DB2에 연결되어 있는지 확인하세요
-- db2 connect to SAMPLE user db2inst1 using password

-- =====================================================
-- 1. 테이블 생성
-- =====================================================

-- 사용자 테이블
CREATE TABLE USERS (
    USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    USER_NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,  -- 암호화 필수
    TEMP_PASSWORD VARCHAR(255),      -- 임시 비밀번호
    STATUS VARCHAR(20) DEFAULT 'ACTIVE', -- ACTIVE, INACTIVE, LOCKED
    IP_RESTRICTION VARCHAR(500),     -- IP 제한 (JSON)
    LAST_LOGIN_TIMESTAMP TIMESTAMP,
    LOGIN_FAIL_COUNT INTEGER DEFAULT 0,  -- 계정 잠금용
    PASSWORD_CHANGE_DATE DATE,
    CREATED_BY VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- 사용자 그룹 테이블
CREATE TABLE USER_GROUPS (
    GROUP_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    GROUP_NAME VARCHAR(100) NOT NULL,
    GROUP_DESCRIPTION VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    CREATED_BY VARCHAR(50),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    MODIFIED_BY VARCHAR(50),
    MODIFIED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- 사용자-그룹 매핑 테이블
CREATE TABLE USER_GROUP_MAPPING (
    USER_ID VARCHAR(50) NOT NULL,
    GROUP_ID VARCHAR(50) NOT NULL,
    ASSIGNED_BY VARCHAR(50),
    ASSIGNED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (USER_ID, GROUP_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID) ON DELETE CASCADE
);

-- SQL 템플릿 권한 테이블
CREATE TABLE SQL_TEMPLATE_PERMISSIONS (
    GROUP_ID VARCHAR(50) NOT NULL,
    TEMPLATE_ID VARCHAR(100) NOT NULL,   -- SQL 파일명
    ACCESS_TYPE VARCHAR(20) DEFAULT 'READ', -- READ, WRITE, DELETE, ADMIN
    FOLDER_PATH VARCHAR(200),            -- 폴더 경로
    GRANTED_BY VARCHAR(50),
    GRANTED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (GROUP_ID, TEMPLATE_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID) ON DELETE CASCADE
);

-- 연결 정보 권한 테이블
CREATE TABLE CONNECTION_PERMISSIONS (
    GROUP_ID VARCHAR(50) NOT NULL,
    CONNECTION_ID VARCHAR(100) NOT NULL,  -- 연결 정보 ID
    ACCESS_TYPE VARCHAR(20) DEFAULT 'READ', -- READ, WRITE, DELETE, ADMIN
    GRANTED_BY VARCHAR(50),
    GRANTED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    PRIMARY KEY (GROUP_ID, CONNECTION_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES USER_GROUPS(GROUP_ID) ON DELETE CASCADE
);

-- 감사 로그 테이블
CREATE TABLE AUDIT_LOGS (
    LOG_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID VARCHAR(50),
    ACTION_TYPE VARCHAR(50) NOT NULL,    -- LOGIN, LOGOUT, CREATE, UPDATE, DELETE, EXECUTE
    RESOURCE_TYPE VARCHAR(50),           -- USER, SQL_TEMPLATE, CONNECTION
    RESOURCE_ID VARCHAR(100),            -- 리소스 ID
    OLD_VALUE CLOB,                      -- 변경 전 값
    NEW_VALUE CLOB,                      -- 변경 후 값
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    SESSION_ID VARCHAR(100),
    EXECUTION_TIME INTEGER,              -- 실행 시간 (ms)
    STATUS VARCHAR(20) DEFAULT 'SUCCESS', -- SUCCESS, FAIL, ERROR
    ERROR_MESSAGE VARCHAR(1000),
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP
);

-- 사용자 세션 테이블
CREATE TABLE USER_SESSIONS (
    SESSION_ID VARCHAR(100) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    IP_ADDRESS VARCHAR(45),
    USER_AGENT VARCHAR(500),
    LOGIN_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    LAST_ACCESS_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,  -- 세션 만료 체크용
    SESSION_DATA CLOB,                   -- 세션 데이터 (JSON)
    STATUS VARCHAR(20) DEFAULT 'ACTIVE', -- ACTIVE, EXPIRED, LOGOUT
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

-- =====================================================
-- 2. 인덱스 생성
-- =====================================================

CREATE INDEX IDX_USERS_STATUS ON USERS(STATUS);
CREATE INDEX IDX_USERS_LAST_LOGIN ON USERS(LAST_LOGIN_TIMESTAMP);
CREATE INDEX IDX_SQL_TEMPLATE_PERMISSIONS_GROUP ON SQL_TEMPLATE_PERMISSIONS(GROUP_ID);
CREATE INDEX IDX_SQL_TEMPLATE_PERMISSIONS_TEMPLATE ON SQL_TEMPLATE_PERMISSIONS(TEMPLATE_ID);
CREATE INDEX IDX_SQL_TEMPLATE_PERMISSIONS_FOLDER ON SQL_TEMPLATE_PERMISSIONS(FOLDER_PATH);
CREATE INDEX IDX_CONNECTION_PERMISSIONS_GROUP ON CONNECTION_PERMISSIONS(GROUP_ID);
CREATE INDEX IDX_CONNECTION_PERMISSIONS_CONN ON CONNECTION_PERMISSIONS(CONNECTION_ID);
CREATE INDEX IDX_AUDIT_LOGS_USER ON AUDIT_LOGS(USER_ID);
CREATE INDEX IDX_AUDIT_LOGS_ACTION ON AUDIT_LOGS(ACTION_TYPE);
CREATE INDEX IDX_AUDIT_LOGS_RESOURCE ON AUDIT_LOGS(RESOURCE_TYPE, RESOURCE_ID);
CREATE INDEX IDX_AUDIT_LOGS_TIMESTAMP ON AUDIT_LOGS(CREATED_TIMESTAMP);
CREATE INDEX IDX_AUDIT_LOGS_IP ON AUDIT_LOGS(IP_ADDRESS);
CREATE INDEX IDX_USER_SESSIONS_USER ON USER_SESSIONS(USER_ID);
CREATE INDEX IDX_USER_SESSIONS_STATUS ON USER_SESSIONS(STATUS);
CREATE INDEX IDX_USER_SESSIONS_LAST_ACCESS ON USER_SESSIONS(LAST_ACCESS_TIMESTAMP);

-- =====================================================
-- 3. 기본 그룹 생성
-- =====================================================

INSERT INTO USER_GROUPS (GROUP_ID, GROUP_NAME, GROUP_DESCRIPTION, STATUS, CREATED_BY, CREATED_TIMESTAMP)
VALUES 
('ADMIN_GROUP', '관리자 그룹', '시스템 관리자 그룹', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP),
('USER_GROUP', '일반 사용자 그룹', '일반 사용자 그룹', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP),
('VIEWER_GROUP', '조회 전용 그룹', '조회만 가능한 사용자 그룹', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 4. 관리자 계정 생성
-- =====================================================

-- 관리자 사용자 생성 (암호화된 비밀번호: 1234)
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, STATUS, CREATED_BY, CREATED_TIMESTAMP)
VALUES ('admin', '관리자', '1e0ce442a8e20cc64b534494d7aea44e', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP);

-- 관리자를 관리자 그룹에 할당
INSERT INTO USER_GROUP_MAPPING (USER_ID, GROUP_ID, ASSIGNED_BY, ASSIGNED_TIMESTAMP)
VALUES ('admin', 'ADMIN_GROUP', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 5. 관리자 권한 설정
-- =====================================================

-- 관리자에게 모든 SQL 템플릿 권한 부여
INSERT INTO SQL_TEMPLATE_PERMISSIONS (GROUP_ID, TEMPLATE_ID, ACCESS_TYPE, FOLDER_PATH, GRANTED_BY, GRANTED_TIMESTAMP)
VALUES ('ADMIN_GROUP', '*', 'ADMIN', '*', 'SYSTEM', CURRENT TIMESTAMP);

-- 관리자에게 모든 연결 정보 권한 부여
INSERT INTO CONNECTION_PERMISSIONS (GROUP_ID, CONNECTION_ID, ACCESS_TYPE, GRANTED_BY, GRANTED_TIMESTAMP)
VALUES ('ADMIN_GROUP', '*', 'ADMIN', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 6. 테스트 사용자 생성 (선택사항)
-- =====================================================

-- 테스트 사용자 생성 (비밀번호: test123)
INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, STATUS, CREATED_BY, CREATED_TIMESTAMP)
VALUES ('testuser', '테스트 사용자', '1e0ce442a8e20cc64b534494d7aea44e', 'ACTIVE', 'SYSTEM', CURRENT TIMESTAMP);

-- 테스트 사용자를 일반 사용자 그룹에 할당
INSERT INTO USER_GROUP_MAPPING (USER_ID, GROUP_ID, ASSIGNED_BY, ASSIGNED_TIMESTAMP)
VALUES ('testuser', 'USER_GROUP', 'SYSTEM', CURRENT TIMESTAMP);

-- =====================================================
-- 7. 생성 확인 쿼리
-- =====================================================

-- 생성된 사용자 확인
SELECT 
    '=== 생성된 사용자 목록 ===' as INFO,
    u.USER_ID,
    u.USER_NAME,
    u.STATUS,
    ug.GROUP_NAME
FROM USERS u
LEFT JOIN USER_GROUP_MAPPING ugm ON u.USER_ID = ugm.USER_ID
LEFT JOIN USER_GROUPS ug ON ugm.GROUP_ID = ug.GROUP_ID
ORDER BY u.USER_ID;

-- 생성된 그룹 확인
SELECT 
    '=== 생성된 그룹 목록 ===' as INFO,
    GROUP_ID,
    GROUP_NAME,
    GROUP_DESCRIPTION,
    STATUS
FROM USER_GROUPS
ORDER BY GROUP_ID;

-- 관리자 권한 확인
SELECT 
    '=== 관리자 권한 확인 ===' as INFO,
    'SQL 템플릿 권한' as PERMISSION_TYPE,
    TEMPLATE_ID,
    ACCESS_TYPE,
    FOLDER_PATH
FROM SQL_TEMPLATE_PERMISSIONS 
WHERE GROUP_ID = 'ADMIN_GROUP'
UNION ALL
SELECT 
    '연결 정보 권한' as PERMISSION_TYPE,
    CONNECTION_ID as TEMPLATE_ID,
    ACCESS_TYPE,
    '' as FOLDER_PATH
FROM CONNECTION_PERMISSIONS 
WHERE GROUP_ID = 'ADMIN_GROUP';

