-- Windmill 비밀번호 정책 마이그레이션 (DB2)
-- 실행: db2 connect to <DB> && db2 -tvf password_policy_migration.sql

-- 비밀번호 변경 이력 (최근 5회 재사용 방지)
CREATE TABLE USER_PASSWORD_HIST (
    HIST_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

CREATE INDEX IDX_USER_PASSWORD_HIST_USER ON USER_PASSWORD_HIST(USER_ID, CREATED_TIMESTAMP DESC);

-- 기존 사용자: 최초 로그인 시 비밀번호 변경 강제 (TEMP_PASSWORD = PASSWORD)
UPDATE USERS
   SET TEMP_PASSWORD = PASSWORD
 WHERE TEMP_PASSWORD IS NULL;
